os: linux
dist: xenial
language: python
cache: pip

jobs:
  include:

    - name: "Tests on python 3.6 (Clinical-db)"
      if: type = pull_request
      python: "3.6.2"   # version in prod170926
      install: pip install . -r requirements-dev.txt
      script: pytest

    - name: "Package install"
      if: type = pull_request
      install: python setup.py install
      script: pip check

    - name: "Node.js & Nuxt"
      if: type = pull_request
      language: node_js
      node_js: 10
      cache:
        yarn: true
        directories: nuxt/node_modules
      before_install: cd nuxt
      install:
        - yarn install
        - yarn build --universal
      script:
        - yarn lint
        - yarn test

    - name: "Development dependencies"
      if: type = pull_request
      install:
        - pip install cython
        - pip install . -r requirements-dev.txt
      script: pip check

    - name: "Production dependencies on python 3.6 (Clinical-db)"
      if: type = pull_request
      python: "3.6.2"             # version in prod170926
      install:
        - pip install pip==9.0.1  # pip version in prod170926
        - pip install cython
        - pip install .
      script: pip check

    - name: "Production dependencies on python 3.7 (Hasta)"
      if: type = pull_request
      python: "3.7.1"           # version in P_main
      install:
        - pip install pip==18.1  # pip version in P_main
        - pip install cython
        - pip install .
      script: pip check

notifications:
  email:
    if: branch = master AND NOT type = push
    on_success: never
    on_failure: always

deploy:
  - provider: pypi
    cleanup: true
    username: __token__
    password:
      secure: "3ohgy8UVFno7gTgTKKdcmzw9xZUsKEjF7Qnjnmx5lbpcR8nBvbpy7RiLtADCyn8bd2cv1jSmwoyxtm+HvL4HnO6u5FUv3FOPo7Nqr8bHuvcepcu7fLR6P0OoMyAwujs2T/Rmk0Q0YYBxuXGYUNkttqGGHDZfgOtP7Xxg0bvR4Wgbb5MDkE8VFWS/xc8465Wa7EvZUsjD/EAqS3UXrhCpohueHaN1IGlto2fBowpMn2vdSYJYlBf+VVFRte5TzMxc2Qj4yixIcnRtCLWqwI/0fz4ctckWCSBbSusXcA45RYnBCx+QbScNvAi8t95RuJMQfnx1SonJis7CmZCykjgGZpUZTLDd0dxHL9+MZl4If/t5bZWwYToi4fCS3XnFsDSyJUyylGPoBZKyRGdK0+nhR3Np4Qeffo9dgq+NSFzv29zEQFyamNkllmX94tNGevx9TPhbAswec+r4Pv6r67hadQpZVwYy07bI+XuKDapihrGcuu3vUdMjpRJdI9Pb1DJfOh827JPFWVoVTLin+pAQpBh1mg0IFD60NLutCOLI3S/bfzUEn/nPNEcggkdLOq+GthqJYx+a0eEpr/hQ+OZtyCaVWhZWzQVltRA9BUjZH3pXHzBlwI52FI+3YyAL5piRGv6OjViefr44LqD4hHmj61yl5Ou4l0g7iBlvXJ0BPxI="
    on:
      tags: true
      branch: master
      distributions: "sdist bdist_wheel"
      repo: Clinical-Genomics/trailblazer
