os: linux
dist: xenial
language: python
cache: pip

jobs:
  include:

    - name: "Node.js & Nuxt"
      if: type = pull_request
      language: node_js
      node_js: 10
      cache:
        yarn: true
        directories: nuxt/node_modules
      before_install: cd nuxt
      install:
        - yarn install
        - yarn build --universal
      script:
        - yarn lint
        - yarn test

notifications:
  email:
    if: branch = master AND NOT type = push
    on_success: never
    on_failure: always
