version: '3.8'

services:
  mysql-server:
    image: mysql:5.6
    container_name: trailblazer-database
    restart: always
    volumes:
      - ../testing/tb_dump:/docker-entrypoint-initdb.d:rw
    ports:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
      MYSQL_DATABASE: trailblazer-stage
    networks:
      - trailblazer-network

  trailblazer:
    image: mropat/trailblazer
    container_name: trailblazer_app
    environment:
      SQLALCHEMY_DATABASE_URI: "mysql+pymysql://user:userpass@mysql-server:3306/trailblazer-stage"
      SCOPE: "DEVELOPMENT"
      GUNICORN_WORKERS: "3"
      GUNICORN_BIND: "0.0.0.0:5000"
      GUNICORN_TIMEOUT: "400"
    ports:
      - 7076:5000
    networks:
      - trailblazer-network
    depends_on:
      - mysql-server

networks:
  trailblazer-network:
    driver: bridge
    ipam:
      driver: default


