name: TB production install clinical-db

on: ["push", "pull_request"]

jobs:

  tests-coverage:

    runs-on: ubuntu-latest

    steps:

    # Check out Trailblazer code
    - uses: actions/checkout@v2


    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.2    # version in prod170926

    - name: Test install on clinical-db
      run: |
        pip install pip==9.0.1
        pip install cython
        pip install .
        pip check

