name: TB production install hasta

on: ["push", "pull_request"]

jobs:

  tests-coverage:

    runs-on: ubuntu-latest

    steps:

    # Check out Trailblazer code
    - uses: actions/checkout@v2


    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.5    # Python version in P_main is 3.7.1, but is not available in actions

    - name: Test install on hasta
      run: |
        pip install pip==18.1
        pip install .
        pip check
    - name: Test install dev on hasta
      run: |
        pip install . -r requirements-dev.txt
        pip check
        pytest
