name: TB production install

on: ["push", "pull_request"]

jobs:

  tests-coverage:

    runs-on: ubuntu-latest

    steps:

    # Check out Trailblazer code
    - uses: actions/checkout@v2

    # Set up python 3.6 on clinical-db
    - name: Test install on clinical-db
      uses: actions/setup-python@v2
      with:
        python-version: '3.6.2'   # version in prod170926
      run: |
        pip install pip==9.0.1
        pip install cython
        pip install .
        pip check
    # Set up python 3.7 on hasta
    - name: Test install on hasta
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.1'   # version in P_main
      run: |
        pip install pip==18.1
        pip install cython
        pip install .
        pip check
